appBringup is ready
imirica/DuplicateFinder pull request #2
Opened 2021-08-13 13:01 UTC by imirica

Please review my appBringup

2021-08-13 13:06 UTC, dmgciubotaru commented
Use this
https://docs.python.org/3/library/tkinter.html#a-simple-hello-world-program
putting it in a class will make it easier to extend later

2021-08-13 13:08 UTC, dmgciubotaru requested changes
use this class instead of plain code

2021-08-13 13:21 UTC, imirica commented
sir, yes sir :))

2021-08-23 08:26 UTC, dmgciubotaru approved these changes

2021-08-23 08:27 UTC, merged